---
sidebar: sidebar 
permalink: install-setup/deploy-hardware.html 
keywords: aide, ai, data engine, ai data engine, dcn, data compute node, afx, afx 1k, install, setup, hardware, deploy, 
summary: レール キットの取り付け方法とキャビネット内のデータ コンピューティング ノードの固定方法について説明します。 
---
= AI Data Engineのデータ計算ノードをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ コンピューティング ノードをキャビネット内に設置して固定します。

.開始する前に
* レール キットに同梱されている手順書があることを確認してください。
* データ コンピューティング ノード、ストレージ システム、およびストレージ シェルフの重量に関連する安全上の懸念事項を理解します。
* ストレージ システムを通る空気の流れは、ベゼルまたはエンド キャップが取り付けられている前面から入り、ポートがある背面から排気されることを理解してください。



NOTE: 一般的に、スイッチはキャビネットの中央に設置する必要があります。ストレージ シェルフは、スイッチの下、2 番目に設置されたスイッチの上に設置する必要があります。コントローラ ノードは、キャビネット内のスイッチの上または下にインストールできます。データ コンピューティング ノードは、キャビネット内のコントローラ ノードの上または下にインストールできます。

.手順
. 必要に応じて、キットに付属の説明書に従って、データ コンピューティング ノード用のレール キットをインストールします。
. データ コンピューティング ノードをキャビネット内に設置して固定します。
+
.. データ コンピューティング ノードをキャビネットの中央のレールに配置し、アプライアンスを下から支えて所定の位置にスライドさせます。
.. 付属の取り付けネジを使用して、data compute nodeをキャビネットに固定します。


. ベゼルをデータ コンピューティング ノードの前面に取り付けます。


.次の手順
データ計算ノードをインストールしたら、link:cable-hardware.html["AIDE のデータ計算ノードをケーブルで接続する"]。
