---
sidebar: sidebar 
permalink: install-setup/prepare-hardware.html 
keywords: aide, ai, data engine, ai data engine, dcn, data compute node, prepare, hardware installation, afx, afx 1k, 
summary: ONTAP環境にAI Data Engineのデータ計算ノードをインストールする準備を行い、ハードウェアを登録してサポート特典にアクセスしてください。 
---
= AI Data Engineのデータコンピューティングノードのインストール準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AI Data Engine のデータコンピューティングノードのインストール準備として、サイトを準備し、箱を開梱して箱の内容を梱包明細書と照合し、サポート特典にアクセスするためにシステムを登録します。



== ステップ1：サイトの準備

データコンピューティングノードをインストールするには、使用する予定のサイトとキャビネットまたはラックが構成の仕様を満たしていることを確認します。

.手順
.  https://hwu.netapp.com["NetApp Hardware Universe"^]を使用して、サイトがデータコンピューティングノードの環境要件と電気要件を満たしていることを確認します。
. 既存の AFX 1K ストレージ システムのインストール内に、データ コンピューティング ノード用の十分なキャビネット スペースがあることを確認します。
+
** データ計算ノードごとに1U
** 各 AFX 1K コントローラーノードに 2U
** 各NX224シェルフに2U
** スイッチモデルに応じて、スイッチあたり1Uまたは2U。






== ステップ2：箱を開ける

データコンピューティングノードに使用する予定のサイトとキャビネットまたはラックが必要な仕様を満たしていることを確認したら、すべてのボックスを開梱し、内容物を梱包明細書の項目と比較します。

.手順
. すべての箱を慎重に開けて、中身を整理して並べます。
. 開梱した品目を梱包明細書と比較し、相違点があれば記録します。
+
配送用カートンの側面にある QR コードをスキャンすると、梱包リストを取得できます。

+
以下の項目は、箱の中に入っている可能性のある内容物の一部です。

+
[cols="12,9,4"]
|===


| *ハードウェア* | *ケーブル* |  


 a| 
** ベゼル
** 説明書付きレールキット
** データコンピューティングノード

 a| 
** 電源コード

|  
|===




== ステップ3：データコンピューティングノードを登録する

サイトがデータコンピューティングノードの仕様要件を満たしていることを確認し、注文した部品がすべて揃っていることを確認したら、システムを登録する必要があります。

.手順
. データコンピューティングノードのシリアル番号を確認します。
+
シリアル番号は次の場所にあります：

+
** 梱包明細書に記載
** 確認メールに記載
** 各データ計算ノード、または一部のシステムでは、各データ計算ノードのシステム管理モジュール。
+
image::../media/drw_ssn_label.svg[システムシリアル番号の例]



.  http://mysupport.netapp.com/["NetAppサポート サイト"^]に移動します。
. ストレージシステムを登録する必要があるかどうかを判断します：
+
[cols="1a,2a"]
|===
| もしあなたが... | 次の手順に従ってください。 


 a| 
NetAppの既存のお客様
 a| 
.. 自身のユーザ名とパスワードでサインインします。
.. *システム* > *マイシステム*を選択します。
.. 新しいシリアル番号がリストされていることを確認します。
.. シリアル番号が記載されていない場合は、新しいNetAppのお客様向けの手順に従ってください。




 a| 
NetAppの新規のお客様
 a| 
.. *今すぐ登録* をクリックしてアカウントを作成します。
.. *Systems* > *Register Systems*を選択します。
.. ストレージシステムのシリアル番号と要求された詳細を入力します。


NetApp が登録を承認すると、必要なソフトウェアをダウンロードできます。承認には最大 24 時間かかります。

|===


.次の手順
データコンピューティングノードをインストールする準備ができたら、link:deploy-hardware.html["データ計算ノードをインストールする"]。
