---
sidebar: sidebar 
permalink: administer/aide-node-replace.html 
keywords:  
summary:  
---
= AIDE クラスタ内のノードを交換する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AI Data Engine（AIDE）クラスタ内のdata compute node（DCN）が機能しなくなった場合、またはハードウェア障害、アップグレード、メンテナンスのために交換が必要な場合は、交換する必要があります。これにより、AIDEクラスタは正常な状態を維持し、稼働し続けます。この手順は、実行中のサービスを中断することなく実行できます。



== ノードの交換の準備

AI Data Engine クラスタ内のノードを交換する前に、考慮すべき点がいくつかあります。

.System Managerのクレデンシャル
AIDE クラスター ノードの置換タスクを実行するには、_ストレージ管理者_権限が必要です。



=== 制限事項

AIDEクラスタ内のノードを交換する際には、以下の制限事項に注意してください：

* ノードの置き換えは、CLIおよびオプションでREST APIを使用する場合にのみサポートされます。
* System Manager を使用してノードの置換を実行することはできません。
* 新しいノードはクラスタのソフトウェアバージョンと一致する必要があります。必要に応じて、ONTAPによって更新されます。
* IP アドレスの競合を避けるため、障害が発生したノードは、クラスタネットワークに接続されている間は電源をオンにしないでください。




=== 要件

次のものが必要になります：

* 新しい交換ノードのシリアル番号




== AIDE クラスタ内の DCN ノードを交換する

次の手順を使用して、AIDEクラスター内のDCNノードを交換できます。

.手順
. 障害が発生したノードを物理的に取り外す
+
ノードの電源をオフにし、クラスタネットワークから切断します。交換プロセス中は、ノードがネットワーク上で起動されていないことを確認してください。

. 次のコマンドを使用して、障害が発生したノードをクラスターから削除します：
+
`dcn cluster node delete -name <node_name> -force true`

+
<node_name>値の実際の名前を入力してください。

. 新しいノードをクラスタに物理的に接続する
+
ノードがケーブル接続され、電源がオンになっており、検出可能であることを確認します。

. 検出可能な未構成のノードを表示して、新しいノードがオンラインであることを確認します：
+
`dcn cluster node show -membership available`

. 次のコマンドを使用して、ノードをクラスターに追加します：
+
`dcn cluster node create -serial-number <new_node_serial>`

+
ONTAPは新しいノードにIPアドレスを割り当てます。ノードのソフトウェアバージョンがクラスタと一致しない場合は、ONTAPによってノードが自動的に更新されます。

. 次のいずれかのコマンドを使用して、クラスタの健全性とノードの統合を確認します：
+
`dcn cluster node show`

+
`dcn cluster node show -instance`



.関連情報
* link:../administer/dcn-add-node.html["コンピューティングクラスターを拡張する"]

