---
sidebar: sidebar 
permalink: administer/upgrades-aide-summary.html 
keywords: update, firmware, system files, automatic updates, ai data engine, aide 
summary: 最新の状態に保つ必要があるAI Data Engineシステムのさまざまなコンポーネントについて学習します。 
---
= AI Data Engineシステムのアップデートと互換性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AI Data Engine（AIDE）システム コンポーネントを最新の状態に維持して、最適なパフォーマンスを維持し、新機能にアクセスできるようにします。デプロイメント後、新しいソフトウェアまたはファームウェアが利用可能になったとき、ノードを追加または交換したとき、または機能更新のために定期的に、コンポーネントを更新します。



== AIDE システム コンポーネント

AIDE システムでアップデートが必要な主なコンポーネントは 2 つあります：ONTAP ソフトウェアと AIDE ソフトウェア（DCN ファームウェアを含む）。



=== ONTAPソフトウェア

ONTAPは、AIDEデプロイメントで使用されるものを含むNetAppストレージシステムで実行されるオペレーティングシステムです。システムの安定性、セキュリティ、およびAIDEコンポーネントとの互換性を維持するために、ONTAPを最新の状態に保ってください。AIDEコンポーネントは個別に更新されます。



=== AIDE ソフトウェア アップデート

AI Data Engine ConsoleソフトウェアとDCNファームウェアのアップデートは、単一のパッケージ（.tgz）として配布され、ONTAPイメージには組み込まれていません。アップデートにより、AI Data Engineシステム内のハードウェアコンポーネントが適切に機能することが保証され、新機能、パフォーマンスの向上、バグ修正が提供されます。



== 更新プロセスを理解する

AIDE ソフトウェア アップデートは ONTAP System Manager を通じて管理できます。

AIDEはONTAP自動ソフトウェア更新機能をサポートしていません。link:https://mysupport.netapp.com/site/downloads["NetApp Support Site ダウンロード"^]から通知を受け取るにはサインアップできますが、AIDEソフトウェアのすべての更新は管理者によって手動で実行されます。

リリースの種類と範囲：

* ONTAPメジャーリリース（9.x.x）とAIDEメジャーリリース（9.x.x U0）では、ONTAP統合に影響する新しい機能、API、または変更が導入されます。
* ONTAPパッチリリース（9.x.x Px）とAIDEアップデートリリース（9.x.x Ux）には、ONTAP統合に影響しない修正プログラムとアップデートが含まれています。




== 互換性マトリックス

アップデートを計画する際は、ONTAPとAI Data Engine softwareの互換性を確認してください。

AIDE ソフトウェアは「U」リリースとしてリリースされます。AIDE メジャー リリースは「U0」リリースであり、後続のマイナー リリースは「U1」以降になります。



=== ONTAPとAI Data Engineの互換性

[cols="1,1"]
|===
| AIDEリリース | サポートされている ONTAP バージョン 


| 9.18.1 U0 | 9.18.1 GA およびすべての 9.18.1 Px 


| 9.18.1 U1 以降 | 9.18.1 GA およびすべての 9.18.1 Px 
|===
[NOTE]
====
「Px」は、メジャー バージョンのすべてのONTAPパッチ リリースを表します（例：9.18.1 P1、9.18.2など）。

====


=== AIDE アップグレード パス

以下の例では、仮想的な将来のバージョンを使用して、AIDE 9.18.1 U0および9.18.1 U1から許可されているアップグレードパスとアップデートパスを示しています。

[cols="25,25,50"]
|===
| 現在の AIDE リリースが… | 対象となるAIDEリリースは… | アップグレードまたは更新パスは… 


| 9.18.1 U0 | 9.18.1 U1 | 直接 


| 9.18.1 U0 | 9.18.1 U3 | 直接（9.18.1 では、任意の Ux から任意の以降の Ux にアップデートできます） 


| 9.18.1 U1 | 9.18.1 U3 | 直接（9.18.1 では、任意の Ux から任意の以降の Ux にアップデートできます） 
|===


== 元に戻す際の制限事項

AIDEシステムは、DCNファームウェア、AIDEソフトウェアアップデート、またはAFXストレージシステム上のONTAPのリバート処理をサポートしていません。アップデートまたはアップグレードをインストールした後は、以前のバージョンに戻すことはできません。アップデートまたはアップグレードする前に<<互換性マトリックス,互換性要件>>を確認してください。

.関連情報
* https://docs.netapp.com/us-en/ontap-afx/administer/upgrade-ontap.html["AFXシステムのONTAPソフトウェアをアップグレードする"^]
* link:update-aide-firmware-software.html["AI Data Engine softwareを更新"]

