---
sidebar: sidebar 
permalink: release-notes/known-limitations.html 
keywords: limitations, known issues, AI Data Engine, AIDE, metadata engine, ONTAP 9.18.1 
summary: 今回のリリースでサポートされていない、または今回のリリースでは正常に機能しないプラットフォーム、デバイス、機能が記載されています。これらの制限事項をよく確認してください。 
---
= AI Data Engineの既知の制限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
今回のリリースでサポートされていない、または今回のリリースでは正常に機能しないプラットフォーム、デバイス、機能が記載されています。これらの制限事項をよく確認してください。



== AIDE 9.18.1初期リリースの既知の制限事項

これらの制限は、AIDE 9.18.1 の Metadata Engine、データコンピュートノード、および管理ワークフローに適用されます。



=== コンピューティングノードの要件と管理

* **最小データコンピューティングノード要件**
+
AIDE クラスタには、Metadata Engine 機能のために最小 3 台、最大 3 台のデータコンピューティングノード（DCN）が必要です。3 台未満の DCN を持つクラスタでは、Metadata Engine 機能を有効にできません。

* **DCN ノードの追加はサポートされていませんNetApp Console を使用**
+
DCN ノードのアップグレードと追加は、NetApp Console ではなく、ONTAP System Manager を使用して実行する必要があります。





=== サポートされているデータソース

* **ONTAP S3バケットまたはStorageGRIDのデータソースとしてのサポートはありません**
+
ONTAPボリューム（ローカルまたはリモート）のみが、ワークスペースおよびメタデータカタログのデータソースとしてサポートされます。ONTAP S3バケットとStorageGRIDオブジェクトはワークスペースに追加できず、このリリースではMetadata Engineによってインデックス化されません。

* **FlexCache ボリュームを使用したワークスペースの作成はサポートされていません**
+
FlexCacheボリュームをデータソースとしてワークスペースに追加することはできません。





=== ソフトウェアの更新と復元の制限

* **DCN ノードのみの手動ソフトウェアアップデート**
+
DCNクラスタの自動ソフトウェアアップデートは、AIDE 9.18.1ではサポートされていません。DCNノードソフトウェアは、ローカルクライアントからイメージをアップロードすることによってのみ更新できます。外部サーバー（HTTP/FTP）からのイメージのダウンロードはサポートされていません。

* **DCN クラスターソフトウェアの復元は不可**
+
DCN クラスタソフトウェアを以前のバージョンに戻すことはできません。以降のバージョンへのアップグレードのみが許可されます。

* **AFX ストレージクラスタの ONTAP リバートなし**
+
AFXストレージクラスタを以前のONTAPバージョンに戻すことはできません。以降のバージョンへのアップグレードのみが許可されます。





=== ワークスペースのライフサイクルとアクセス構成

* **ワークスペースのソフト削除または復元はできません**
+
ワークスペースの削除は永続的です。削除されたワークスペースを復元するオプションはありません。

* **初期クラスタセットアップ中の OIDC 構成はサポートされません**
+
OIDC/OAuthの設定は、クラスタ作成後にONTAP System Managerを使用して実行する必要があります。



.関連情報
* link:whats-new.html["AI Data Engineの新機能"]

